global using System;
global using System.IO;
global using System.Security.Permissions;
global using System.Collections.Generic;
global using System.Linq;
global using RWCustom;
global using UnityEngine;
global using Mono.Cecil.Cil;
global using MonoMod.Cil;
global using Random = UnityEngine.Random;
global using BepInEx;
global using DevInterface;
global using CreatureType = CreatureTemplate.Type;
global using static PathCost.Legality;
global using Fisobs.Core;
global using Fisobs.Creatures;
global using Fisobs.Sandbox;
global using Fisobs.Items;
global using Fisobs.Properties;
global using SlugBase.DataTypes;
global using System.Runtime.CompilerServices;
global using static Player;
global using DressMySlugcat;
global using static MoreSlugcats.SingularityBomb;
global using System.Reflection;
global using MoreSlugcats;
global using Menu.Remix.MixedUI;
global using HUD;
global using VoidSea;

[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]